name: 'Embr Action'
description: 'GitHub Action that creates Embr builds with auto-captured branch and commit information'
author: 'surenderssm'

inputs:
  mode:
    description: 'Action mode: "build" (create build from branch/commit) or "upload" (upload zip file)'
    required: false
    default: 'build'
  project-id:
    description: 'The Embr project ID'
    required: true
  environment-id:
    description: 'The Embr environment ID (required for upload mode)'
    required: false
  zip-file:
    description: 'Path to the zip file to upload (required for upload mode)'
    required: false
  api-base-url:
    description: 'Base URL for the Embr API'
    required: false
    default: 'https://embr-poc.azurewebsites.net/api'

outputs:
  status:
    description: 'Status of the build (succeeded, failed, timeout)'
  build-id:
    description: 'The unique build ID'
  build-number:
    description: 'The build number'
  log-path:
    description: 'Path to the build logs'
  deployment-url:
    description: 'URL where the app is deployed'
  response:
    description: 'Full JSON response from the Embr API'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'orange'
