name: 'Embr Action'
description: 'GitHub Action that creates Embr builds with auto-captured branch and commit information'
author: 'surenderssm'

inputs:
  project-id:
    description: 'The Embr project ID'
    required: true

outputs:
  status:
    description: 'Status of the build (succeeded, failed, timeout)'
  build-id:
    description: 'The unique build ID'
  build-number:
    description: 'The build number'
  log-path:
    description: 'Path to the build logs'
  deployment-url:
    description: 'URL where the app is deployed'
  response:
    description: 'Full JSON response from the Embr API'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'orange'
