name: 'Embr Action'
description: 'GitHub Action that creates Embr builds with auto-captured branch and commit information'
author: 'surenderssm'

inputs:
  project-id:
    description: 'The Embr project ID'
    required: true
  api-base-url:
    description: 'The API base URL (default: https://embr-poc.azurewebsites.net/api)'
    required: false
    default: 'https://embr-poc.azurewebsites.net/api'

outputs:
  status:
    description: 'Status of the build execution'
  response:
    description: 'Response from the Embr API'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'orange'
